url: ""
baseurl: ""
destination: _site
robots: noindex,nofollow
environment: 'development'
future: true

sass:
  style: uncompressed

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/en"
      locale: en_US
  -
    scope:
      type: "posts"
    values:
      layout: post
