# Site configuration

title: Le blog de Sud Web
timezone: Europe/Paris

url: https://sudweb.fr
repository: sudweb/blog
baseurl: /blog
destination: _site/blog
locale: fr_FR
contact: https://sudweb.fr/2018/contact
logo: https://sudweb.fr/blog/assets/images/social/sudweb-logo.jpg
lazyload:
  placeholder: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
compress_html:
  ignore:
    envs:
      - 'development'

## SEO

robots: index,follow

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/blog/en"
      locale: en_US
  -
    scope:
      type: "posts"
    values:
      layout: post

permalink: "/:categories/:title/"

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

logo: /assets/images/twittercard.png

microtypo:
  median: true

include:
  - _headers

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script
  - vendor
  - "Rakefile"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
